name: Tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: ✅ Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      # - run: cargo fmt -- --check
      - run: cargo clippy --all --all-targets --all-features
      - run: cargo test
      - run: cargo build --release
